{
  "packages":
    [
      "api/*",
      "configuration/*",
      "design/*",
      "development/*",
      "devops/*",
      "namespaces/*",
      "products/*",
      "testing/*",
      "integrations/*",
      "framework-sdks/*"
    ]
}
