// `TNL__`-prefixed variable aliases
export const tnlVariables = {
	TNL__callerExecutionEventId: 'TNL__C',
	TNL__arg: 'TNL__a',
	TNL__args: 'TNL__A',
	TNL__firstArg: 'TNL__f',
	TNL__symbol: 'TNL__s',
	TNL__functionInvokedEvents: 'TNL__G',
	TNL__isMissingFirstParameter: 'TNL__m',
	TNL__isOverloadedFirstArg: 'TNL__o',
	TNL__currentFunctionScopeInvokedEventId: 'TNL__i',
} as const;

// `TNL__` property aliases
export const tnlProperties = {
	setElementDomNodeEventIdFromXpath: 'a',
	sourceToRenderEventIdMap: 'b',
	idpState: 'c',
	functionEventsMap: 'd',
	getEvent: 'e',
	createEvent: 'f',
	createGlobalInvokedEvent: 'g',

	overloadedFunctionReferenceToFunctionId: 'h',

	tempFunctionEntry: 'i',
	jsxDEVFunctions: 'j',
	registerOverloadedFunction: 'k',
	newTrace: 'l',
	handleFunctionInvocation: 'm',
	getInstrumentedCode: 'n',
	getArgumentString: 'o',
	getTransformedCodeFromAstNode: 'p',
	getFirstParameterIdentifier: 'q',
	getNamedParameterPatternWithRight: 'r',
	getParameterPatternWithoutRight: 's',
	getNamedParameterPatternWithoutRight: 't',
	getParameterRight: 'u',
	originalEval: 'v',
	propertyCallee: 'w',
	exprCallee: 'x',
	callExpression: 'y',
	getEvalInstrumentedCode: 'z',
	onetime: 'A',
	patchedEval: 'B',
	acorn: 'C',
	walk: 'D',
	js: 'E',
	getCurrentLocation: 'F',
	escapeStringRegexp: 'G',
	getParameterPatternWithRight: 'H',
	nanoid: 'I',
	getTemporaryStorageFolderPath: 'J',
	elementDomNodeToEventId: 'K',
} as const;
