import { defineBinStub } from '#utils/define.ts';

/**
	We modify the pkgx executable to set the PATH variable to prioritize our bin stubs to the passthrough command it runs
*/
export const tunnelEnv = defineBinStub({
	commandName: '_tunnel_env',
	async getStub() {
		return String.raw`#!/bin/sh

##########################################################################
# DO NOT EDIT DIRECTLY; this file is generated by \`bin-stubs/generate\` #
##########################################################################

# This script emulates the behavior of the 'env' command in a POSIX-compliant shell
# It sets environment variables and then executes a command

while [ $# -gt 0 ]; do
    case "$1" in
        *=*)    # If the argument is an environment variable assignment
            export "$1"
            shift
            ;;
        *)      # If we hit a non-environment variable, the rest of the arguments are the command
            exec "$@"
            ;;
    esac
done
`;
	},
});
